#!/bin/bash
CONFIG_VARIABLES="PASSWORD NOVA_ENDPOINT IRM_INTERFACE CRS_URL IMAGE_NAME DEFAULT_IMAGE"

# configuring irm-nova
for varname in ${CONFIG_VARIABLES}; do
    varvalue=$(eval "echo \${$varname}")
    if [ -n "$varvalue" ]; then
        sed -i "/^$varname:/s/:.*$/: $varvalue/" /harness/cfg/irm-nova.cfg 
    fi
done

supervisord -n -c cfg/supervisord.conf 
sleep 1
supervisorctl start publisher zmq_device display
curl -X POST http://localhost:6000/registerPath -H "Content-Type: application/json" -d "{\"LoggingPath\":[\"/harness/crs/crs.log\"]}"
sleep 1
supervisorctl start crs
supervisorctl start irm-nova
#supervisorctl start irm-shepard

